Add basic webpack build.
Squashed commit of the following:

commit 78dd9524df9bb5aea6c019091d123d80b22d9be3
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Tue Mar 31 23:33:34 2020 -0500

    Update docs.

commit 19924d92a954e6e70877c43663601e1583b9662c
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Tue Mar 31 23:17:26 2020 -0500

    Finish up first revision.

commit 3699508dc5b54643b33aba91a969ae64ef2f9c4d
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Sun Mar 29 22:49:16 2020 -0500

    Adjust path.

commit dda8c4518eb250871158cfaaa7a8e54c2813b21c
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Sun Mar 29 21:52:13 2020 -0500

    Add sass/css/style loaders.

commit 9b79ba78da70a77125598e29aef06844ebcaeb00
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Sun Mar 29 16:44:33 2020 -0500

    add sass loader according to error.

    ERROR in ./src/components/TestComponent.vue?vue&type=style&index=0&id=5bfff48d&lang=sass&scoped=true (./node_modules/vue-loader/dist??ref--6-0!./src/components/TestComponent.vue?vue&type=style&index=0&id=5bfff48d&lang=sass&scoped=true) 2:2
    Module parse failed: Unexpected token (2:2)
    File was processed with these loaders:
     * ./node_modules/vue-loader/dist/index.js
    You may need an additional loader to handle the result of these loaders.
    |
    >   .test-class
    |     background: red

commit dc0789a8e5e4f5043e2a1a60b46a17af4b131a93
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Sun Mar 29 16:19:32 2020 -0500

    Add VueLoaderPlugin according to error in the build.

    ERROR in ./src/components/TestComponent.vue
    Module Error (from ./node_modules/vue-loader/dist/index.js):
    vue-loader was used without the corresponding plugin. Make sure to include VueLoaderPlugin in your webpack config.
     @ ./src/index.js 3:0-58 5:0-24

commit 29c2d447c1282de5b1494e9430e46955c0cc5559
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Sun Mar 29 16:16:43 2020 -0500

    Add vue/compiler-sfc according to error in the build.

    ERROR in ./src/components/TestComponent.vue
    Module build failed (from ./node_modules/vue-loader/dist/index.js):
    Error: vue-loader requires @vue/compiler-sfc to be present in the dependency tree.

commit 659eded9b0884e846e17b43477d536e91f2d11bd
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Sun Mar 29 16:04:11 2020 -0500

    add vue loader

commit 232d393d233dd91a7c61a7c982992b9b7ef013d2
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Sun Mar 29 15:40:20 2020 -0500

    add webpack.

commit 0664ff4ff5be67b822e65333352e6f93858ef958
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Sun Mar 29 14:39:54 2020 -0500

    Add vue 3 as dev dependency.

commit d07d78eb525a08c2e4067c4e12c7be99d6520808
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Fri Mar 27 01:47:28 2020 -0500

    delete rollup.

commit 8378c640df8e2d3e3bd95fcaacecc7d3d4fbae76
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Fri Mar 27 01:43:43 2020 -0500

    rollup wip. Not working yet

    See: https://github.com/vuejs/rollup-plugin-vue/issues/322. Run into the
    following error:

    ➜  vue-material-components git:(basic-build) ✗ yarn build
    yarn run v1.22.4
    $ rollup -c --environment BUILD:production
    [!] Error: Cannot find module 'vue-template-compiler'
    Require stack:
    - vue-material-components/node_modules/@vue/component-compiler/dist/compiler.js
    - vue-material-components/node_modules/@vue/component-compiler/dist/index.js
    - vue-material-components/node_modules/rollup-plugin-vue/dist/rollup-plugin-vue.js
    - vue-material-components/rollup.config.js
    - vue-material-components/node_modules/rollup/dist/bin/rollup

commit f45b1dd7c05b2a762ef7158529e81518d381e295
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Fri Mar 27 00:58:55 2020 -0500

    Add rollup plugin vue as dev dependency.

commit e2a3dc7c2ecd2f46464a24a1fffc6aea692e0a63
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Fri Mar 27 00:53:45 2020 -0500

    Add rollup dev dependency.

commit 4bd21bd6d4801017fed099142c15299e1fe3a386
Author: Liang Zhou <lzhoucs@gmail.com>
Date:   Fri Mar 27 00:47:36 2020 -0500

    set up test files.